using FAM.Infrastructure.Common.Seeding;
using FAM.Infrastructure.PersistenceModels.Ef;

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace FAM.Infrastructure.Providers.PostgreSQL.Seeders;

/// <summary>
/// Seeds initial countries data (Sorted A-Z)
/// </summary>
public class CountrySeeder : BaseDataSeeder
{
    private readonly PostgreSqlDbContext _dbContext;

    public CountrySeeder(PostgreSqlDbContext dbContext, ILogger<CountrySeeder> logger)
        : base(logger)
    {
        _dbContext = dbContext;
    }

    public override string Name => "20251129140005_CountrySeeder";

    public override async Task SeedAsync(CancellationToken cancellationToken = default)
    {
        LogInfo("Checking for existing countries...");

        var hasCountries = await _dbContext.Countries.AnyAsync(cancellationToken);

        if (hasCountries)
        {
            LogInfo("Countries already exist, skipping seed");
            return;
        }

        LogInfo("Seeding countries...");

        var countries = new List<CountryEf>
        {
            CreateCountry("AF", "AFG", "004", "Afghanistan", "Afghanistan", "Islamic Republic of Afghanistan",
                "Asia", "Southern Asia", "Asia", 33.9391m, 67.7100m,
                "+93", ".af", "AFN", "Afghan Afghani", "؋",
                "ps", "Pashto,Dari", "Kabul", "Afghan",
                "Asia/Kabul", "🇦🇫", 38928341, 652230m),
            CreateCountry("AL", "ALB", "008", "Albania", "Shqipëria", "Republic of Albania",
                "Europe", "Southern Europe", "Europe", 41.1533m, 20.1683m,
                "+355", ".al", "ALL", "Lek", "L",
                "sq", "Albanian", "Tirana", "Albanian",
                "Europe/Tirane", "🇦🇱", 2837743, 28748m),
            CreateCountry("DZ", "DZA", "012", "Algeria", "Dzayer", "People's Democratic Republic of Algeria",
                "Africa", "Northern Africa", "Africa", 28.0339m, 1.6596m,
                "+213", ".dz", "DZD", "Algerian Dinar", "د.ج",
                "ar", "Arabic", "Algiers", "Algerian",
                "Africa/Algiers", "🇩🇿", 43851043, 2381741m),
            CreateCountry("AD", "AND", "020", "Andorra", "Andorra", "Principality of Andorra",
                "Europe", "Southern Europe", "Europe", 42.5063m, 1.5218m,
                "+376", ".ad", "EUR", "Euro", "€",
                "ca", "Catalan", "Andorra la Vella", "Andorran",
                "Europe/Andorra", "🇦🇩", 77265, 468m),
            CreateCountry("AO", "AGO", "024", "Angola", "Angola", "Republic of Angola",
                "Africa", "Middle Africa", "Africa", -11.2027m, 17.8739m,
                "+244", ".ao", "AOA", "Kwanza", "Kz",
                "pt", "Portuguese", "Luanda", "Angolan",
                "Africa/Luanda", "🇦🇴", 32866268, 1246700m),
            CreateCountry("AG", "ATG", "028", "Antigua and Barbuda", "Antigua and Barbuda", "Antigua and Barbuda",
                "Americas", "Caribbean", "North America", 17.0608m, -61.7964m,
                "+1-268", ".ag", "XCD", "East Caribbean Dollar", "$",
                "en", "English", "Saint John's", "Antiguan",
                "America/Antigua", "🇦🇬", 97928, 442m),
            CreateCountry("AR", "ARG", "032", "Argentina", "Argentina", "Argentine Republic",
                "Americas", "South America", "South America", -38.4161m, -63.6167m,
                "+54", ".ar", "ARS", "Argentine Peso", "$",
                "es", "Spanish", "Buenos Aires", "Argentine",
                "America/Argentina/Buenos_Aires", "🇦🇷", 45195774, 2780400m),
            CreateCountry("AM", "ARM", "051", "Armenia", "Hayastan", "Republic of Armenia",
                "Asia", "Western Asia", "Asia", 40.0691m, 45.0382m,
                "+374", ".am", "AMD", "Armenian Dram", "֏",
                "hy", "Armenian", "Yerevan", "Armenian",
                "Asia/Yerevan", "🇦🇲", 2963234, 29743m),
            CreateCountry("AU", "AUS", "036", "Australia", "Australia", "Commonwealth of Australia",
                "Oceania", "Australia and New Zealand", "Oceania", -25.2744m, 133.7751m,
                "+61", ".au", "AUD", "Australian Dollar", "$",
                "en", "English", "Canberra", "Australian",
                "Australia/Sydney", "🇦🇺", 25499884, 7692024m),
            CreateCountry("AT", "AUT", "040", "Austria", "Österreich", "Republic of Austria",
                "Europe", "Western Europe", "Europe", 47.5162m, 14.5501m,
                "+43", ".at", "EUR", "Euro", "€",
                "de", "German", "Vienna", "Austrian",
                "Europe/Vienna", "🇦🇹", 9006400, 83871m, true),
            CreateCountry("AZ", "AZE", "031", "Azerbaijan", "Azərbaycan", "Republic of Azerbaijan",
                "Asia", "Western Asia", "Asia", 40.1431m, 47.5769m,
                "+994", ".az", "AZN", "Azerbaijani Manat", "₼",
                "az", "Azerbaijani", "Baku", "Azerbaijani",
                "Asia/Baku", "🇦🇿", 10110116, 86600m),
            CreateCountry("BS", "BHS", "044", "Bahamas", "Bahamas", "Commonwealth of the Bahamas",
                "Americas", "Caribbean", "North America", 25.0343m, -77.3963m,
                "+1-242", ".bs", "BSD", "Bahamian Dollar", "$",
                "en", "English", "Nassau", "Bahamian",
                "America/Nassau", "🇧🇸", 393248, 13943m),
            CreateCountry("BH", "BHR", "048", "Bahrain", "Bahrain", "Kingdom of Bahrain",
                "Asia", "Western Asia", "Asia", 26.0667m, 50.5577m,
                "+973", ".bh", "BHD", "Bahraini Dinar", ".د.ب",
                "ar", "Arabic", "Manama", "Bahraini",
                "Asia/Bahrain", "🇧🇭", 1701583, 765m),
            CreateCountry("BD", "BGD", "050", "Bangladesh", "Bangladesh", "People's Republic of Bangladesh",
                "Asia", "Southern Asia", "Asia", 23.6850m, 90.3563m,
                "+880", ".bd", "BDT", "Bangladeshi Taka", "৳",
                "bn", "Bengali", "Dhaka", "Bangladeshi",
                "Asia/Dhaka", "🇧🇩", 164689383, 147570m),
            CreateCountry("BB", "BRB", "052", "Barbados", "Barbados", "Barbados",
                "Americas", "Caribbean", "North America", 13.1939m, -59.5432m,
                "+1-246", ".bb", "BBD", "Barbados Dollar", "$",
                "en", "English", "Bridgetown", "Barbadian",
                "America/Barbados", "🇧🇧", 287371, 430m),
            CreateCountry("BY", "BLR", "112", "Belarus", "Беларусь", "Republic of Belarus",
                "Europe", "Eastern Europe", "Europe", 53.7098m, 27.9534m,
                "+375", ".by", "BYN", "Belarusian Ruble", "Br",
                "be", "Belarusian,Russian", "Minsk", "Belarusian",
                "Europe/Minsk", "🇧🇾", 9398861, 207600m),
            CreateCountry("BE", "BEL", "056", "Belgium", "België", "Kingdom of Belgium",
                "Europe", "Western Europe", "Europe", 50.5039m, 4.4699m,
                "+32", ".be", "EUR", "Euro", "€",
                "nl", "Dutch,French,German", "Brussels", "Belgian",
                "Europe/Brussels", "🇧🇪", 11589616, 30528m, true),
            CreateCountry("BZ", "BLZ", "084", "Belize", "Belize", "Belize",
                "Americas", "Central America", "North America", 17.1899m, -88.4976m,
                "+501", ".bz", "BZD", "Belize Dollar", "$",
                "en", "English", "Belmopan", "Belizean",
                "America/Belize", "🇧🇿", 397621, 22966m),
            CreateCountry("BJ", "BEN", "204", "Benin", "Bénin", "Republic of Benin",
                "Africa", "Western Africa", "Africa", 9.3077m, 2.3158m,
                "+229", ".bj", "XOF", "West African CFA Franc", "Fr",
                "fr", "French", "Porto-Novo", "Beninese",
                "Africa/Porto-Novo", "🇧🇯", 12123198, 114763m),
            CreateCountry("BT", "BTN", "064", "Bhutan", "Druk Yul", "Kingdom of Bhutan",
                "Asia", "Southern Asia", "Asia", 27.5142m, 90.4336m,
                "+975", ".bt", "BTN", "Ngultrum", "Nu.",
                "dz", "Dzongkha", "Thimphu", "Bhutanese",
                "Asia/Thimphu", "🇧🇹", 771612, 38394m),
            CreateCountry("BO", "BOL", "068", "Bolivia", "Bolivia", "Plurinational State of Bolivia",
                "Americas", "South America", "South America", -16.2902m, -63.5887m,
                "+591", ".bo", "BOB", "Boliviano", "Bs.",
                "es", "Spanish,Quechua,Aymara", "Sucre", "Bolivian",
                "America/La_Paz", "🇧🇴", 11673029, 1098581m),
            CreateCountry("BA", "BIH", "070", "Bosnia and Herzegovina", "Bosna i Hercegovina", "Bosnia and Herzegovina",
                "Europe", "Southern Europe", "Europe", 43.9159m, 17.6791m,
                "+387", ".ba", "BAM", "Convertible Mark", "KM",
                "bs", "Bosnian,Croatian,Serbian", "Sarajevo", "Bosnian",
                "Europe/Sarajevo", "🇧🇦", 3280819, 51209m),
            CreateCountry("BW", "BWA", "072", "Botswana", "Botswana", "Republic of Botswana",
                "Africa", "Southern Africa", "Africa", -22.3285m, 24.6849m,
                "+267", ".bw", "BWP", "Pula", "P",
                "en", "English,Tswana", "Gaborone", "Motswana",
                "Africa/Gaborone", "🇧🇼", 2351625, 581730m),
            CreateCountry("BR", "BRA", "076", "Brazil", "Brasil", "Federative Republic of Brazil",
                "Americas", "South America", "South America", -14.2350m, -51.9253m,
                "+55", ".br", "BRL", "Brazilian Real", "R$",
                "pt", "Portuguese", "Brasília", "Brazilian",
                "America/Sao_Paulo", "🇧🇷", 212559417, 8515767m),
            CreateCountry("BN", "BRN", "096", "Brunei", "Brunei", "Nation of Brunei",
                "Asia", "South-Eastern Asia", "Asia", 4.5353m, 114.7277m,
                "+673", ".bn", "BND", "Brunei Dollar", "$",
                "ms", "Malay", "Bandar Seri Begawan", "Bruneian",
                "Asia/Brunei", "🇧🇳", 437479, 5765m),
            CreateCountry("BG", "BGR", "100", "Bulgaria", "България", "Republic of Bulgaria",
                "Europe", "Eastern Europe", "Europe", 42.7339m, 25.4858m,
                "+359", ".bg", "BGN", "Bulgarian Lev", "лв",
                "bg", "Bulgarian", "Sofia", "Bulgarian",
                "Europe/Sofia", "🇧🇬", 6948445, 110879m, true),
            CreateCountry("BF", "BFA", "854", "Burkina Faso", "Burkina Faso", "Burkina Faso",
                "Africa", "Western Africa", "Africa", 12.2383m, -1.5616m,
                "+226", ".bf", "XOF", "West African CFA Franc", "Fr",
                "fr", "French", "Ouagadougou", "Burkinabé",
                "Africa/Ouagadougou", "🇧🇫", 20903278, 274200m),
            CreateCountry("BI", "BDI", "108", "Burundi", "Burundi", "Republic of Burundi",
                "Africa", "Eastern Africa", "Africa", -3.3731m, 29.9189m,
                "+257", ".bi", "BIF", "Burundian Franc", "Fr",
                "fr", "Kirundi,French,English", "Gitega", "Burundian",
                "Africa/Bujumbura", "🇧🇮", 11890781, 27834m),
            CreateCountry("CV", "CPV", "132", "Cabo Verde", "Cabo Verde", "Republic of Cabo Verde",
                "Africa", "Western Africa", "Africa", 16.0021m, -24.0131m,
                "+238", ".cv", "CVE", "Escudo", "Esc",
                "pt", "Portuguese", "Praia", "Cabo Verdean",
                "Atlantic/Cape_Verde", "🇨🇻", 555988, 4033m),
            CreateCountry("KH", "KHM", "116", "Cambodia", "កម្ពុជា", "Kingdom of Cambodia",
                "Asia", "South-Eastern Asia", "Asia", 12.5657m, 104.9910m,
                "+855", ".kh", "KHR", "Cambodian Riel", "៛",
                "km", "Khmer", "Phnom Penh", "Cambodian",
                "Asia/Phnom_Penh", "🇰🇭", 16718965, 181035m),
            CreateCountry("CM", "CMR", "120", "Cameroon", "Cameroun", "Republic of Cameroon",
                "Africa", "Middle Africa", "Africa", 7.3697m, 12.3547m,
                "+237", ".cm", "XAF", "Central African CFA Franc", "Fr",
                "fr", "French,English", "Yaoundé", "Cameroonian",
                "Africa/Douala", "🇨🇲", 26545864, 475442m),
            CreateCountry("CA", "CAN", "124", "Canada", "Canada", "Canada",
                "Americas", "Northern America", "North America", 56.1304m, -106.3468m,
                "+1", ".ca", "CAD", "Canadian Dollar", "$",
                "en", "English,French", "Ottawa", "Canadian",
                "America/Toronto", "🇨🇦", 37742154, 9984670m),
            CreateCountry("CF", "CAF", "140", "Central African Republic", "République centrafricaine",
                "Central African Republic",
                "Africa", "Middle Africa", "Africa", 6.6111m, 20.9394m,
                "+236", ".cf", "XAF", "Central African CFA Franc", "Fr",
                "fr", "French,Sango", "Bangui", "Central African",
                "Africa/Bangui", "🇨🇫", 4829764, 622984m),
            CreateCountry("TD", "TCD", "148", "Chad", "Tchad", "Republic of Chad",
                "Africa", "Middle Africa", "Africa", 15.4542m, 18.7322m,
                "+235", ".td", "XAF", "Central African CFA Franc", "Fr",
                "fr", "French,Arabic", "N'Djamena", "Chadian",
                "Africa/Ndjamena", "🇹🇩", 16425859, 1284000m),
            CreateCountry("CL", "CHL", "152", "Chile", "Chile", "Republic of Chile",
                "Americas", "South America", "South America", -35.6751m, -71.5430m,
                "+56", ".cl", "CLP", "Chilean Peso", "$",
                "es", "Spanish", "Santiago", "Chilean",
                "America/Santiago", "🇨🇱", 19116201, 756102m),
            CreateCountry("CN", "CHN", "156", "China", "中国", "People's Republic of China",
                "Asia", "Eastern Asia", "Asia", 35.8617m, 104.1954m,
                "+86", ".cn", "CNY", "Chinese Yuan", "¥",
                "zh", "Mandarin", "Beijing", "Chinese",
                "Asia/Shanghai", "🇨🇳", 1439323776, 9596960m),
            CreateCountry("CO", "COL", "170", "Colombia", "Colombia", "Republic of Colombia",
                "Americas", "South America", "South America", 4.5709m, -74.2973m,
                "+57", ".co", "COP", "Colombian Peso", "$",
                "es", "Spanish", "Bogotá", "Colombian",
                "America/Bogota", "🇨🇴", 50882891, 1141748m),
            CreateCountry("KM", "COM", "174", "Comoros", "Komori", "Union of the Comoros",
                "Africa", "Eastern Africa", "Africa", -11.8750m, 43.8722m,
                "+269", ".km", "KMF", "Comorian Franc", "Fr",
                "fr", "Comorian,Arabic,French", "Moroni", "Comorian",
                "Indian/Comoro", "🇰🇲", 869595, 1862m),
            CreateCountry("CG", "COG", "178", "Congo", "Congo-Brazzaville", "Republic of the Congo",
                "Africa", "Middle Africa", "Africa", -0.2280m, 15.8277m,
                "+242", ".cg", "XAF", "Central African CFA Franc", "Fr",
                "fr", "French", "Brazzaville", "Congolese",
                "Africa/Brazzaville", "🇨🇬", 5518092, 342000m),
            CreateCountry("CR", "CRI", "188", "Costa Rica", "Costa Rica", "Republic of Costa Rica",
                "Americas", "Central America", "North America", 9.7489m, -83.7534m,
                "+506", ".cr", "CRC", "Costa Rican Colón", "₡",
                "es", "Spanish", "San José", "Costa Rican",
                "America/Costa_Rica", "🇨🇷", 5094114, 51100m),
            CreateCountry("HR", "HRV", "191", "Croatia", "Hrvatska", "Republic of Croatia",
                "Europe", "Southern Europe", "Europe", 45.1000m, 15.2000m,
                "+385", ".hr", "EUR", "Euro", "€",
                "hr", "Croatian", "Zagreb", "Croatian",
                "Europe/Zagreb", "🇭🇷", 4047200, 56594m, true),
            CreateCountry("CU", "CUB", "192", "Cuba", "Cuba", "Republic of Cuba",
                "Americas", "Caribbean", "North America", 21.5218m, -77.7812m,
                "+53", ".cu", "CUP", "Cuban Peso", "$",
                "es", "Spanish", "Havana", "Cuban",
                "America/Havana", "🇨🇺", 11326616, 109884m),
            CreateCountry("CY", "CYP", "196", "Cyprus", "Κύπρος", "Republic of Cyprus",
                "Europe", "Southern Europe", "Europe", 35.1264m, 33.4299m,
                "+357", ".cy", "EUR", "Euro", "€",
                "el", "Greek,Turkish", "Nicosia", "Cypriot",
                "Asia/Nicosia", "🇨🇾", 1207359, 9251m, true),
            CreateCountry("CZ", "CZE", "203", "Czechia", "Česko", "Czech Republic",
                "Europe", "Eastern Europe", "Europe", 49.8175m, 15.4730m,
                "+420", ".cz", "CZK", "Czech Koruna", "Kč",
                "cs", "Czech", "Prague", "Czech",
                "Europe/Prague", "🇨🇿", 10693939, 78865m, true),
            CreateCountry("DK", "DNK", "208", "Denmark", "Danmark", "Kingdom of Denmark",
                "Europe", "Northern Europe", "Europe", 56.2639m, 9.5018m,
                "+45", ".dk", "DKK", "Danish Krone", "kr",
                "da", "Danish", "Copenhagen", "Danish",
                "Europe/Copenhagen", "🇩🇰", 5831404, 43094m, true),
            CreateCountry("DJ", "DJI", "262", "Djibouti", "Djibouti", "Republic of Djibouti",
                "Africa", "Eastern Africa", "Africa", 11.8251m, 42.5903m,
                "+253", ".dj", "DJF", "Djiboutian Franc", "Fr",
                "fr", "French,Arabic", "Djibouti", "Djiboutian",
                "Africa/Djibouti", "🇩🇯", 988002, 23200m),
            CreateCountry("DM", "DMA", "212", "Dominica", "Dominica", "Commonwealth of Dominica",
                "Americas", "Caribbean", "North America", 15.4150m, -61.3710m,
                "+1-767", ".dm", "XCD", "East Caribbean Dollar", "$",
                "en", "English", "Roseau", "Dominican",
                "America/Dominica", "🇩🇲", 71991, 751m),
            CreateCountry("DO", "DOM", "214", "Dominican Republic", "República Dominicana", "Dominican Republic",
                "Americas", "Caribbean", "North America", 18.7357m, -70.1627m,
                "+1-809", ".do", "DOP", "Dominican Peso", "RD$",
                "es", "Spanish", "Santo Domingo", "Dominican",
                "America/Santo_Domingo", "🇩🇴", 10847904, 48671m),
            CreateCountry("CD", "COD", "180", "DR Congo", "Congo-Kinshasa", "Democratic Republic of the Congo",
                "Africa", "Middle Africa", "Africa", -4.0383m, 21.7587m,
                "+243", ".cd", "CDF", "Congolese Franc", "Fr",
                "fr", "French", "Kinshasa", "Congolese",
                "Africa/Kinshasa", "🇨🇩", 89561404, 2344858m),
            CreateCountry("EC", "ECU", "218", "Ecuador", "Ecuador", "Republic of Ecuador",
                "Americas", "South America", "South America", -1.8312m, -78.1834m,
                "+593", ".ec", "USD", "US Dollar", "$",
                "es", "Spanish", "Quito", "Ecuadorian",
                "America/Guayaquil", "🇪🇨", 17643060, 283561m),
            CreateCountry("EG", "EGY", "818", "Egypt", "مصر", "Arab Republic of Egypt",
                "Africa", "Northern Africa", "Africa", 26.8206m, 30.8025m,
                "+20", ".eg", "EGP", "Egyptian Pound", "£",
                "ar", "Arabic", "Cairo", "Egyptian",
                "Africa/Cairo", "🇪🇬", 102334404, 1002450m),
            CreateCountry("SV", "SLV", "222", "El Salvador", "El Salvador", "Republic of El Salvador",
                "Americas", "Central America", "North America", 13.7942m, -88.8965m,
                "+503", ".sv", "USD", "US Dollar", "$",
                "es", "Spanish", "San Salvador", "Salvadoran",
                "America/El_Salvador", "🇸🇻", 6486201, 21041m),
            CreateCountry("GQ", "GNQ", "226", "Equatorial Guinea", "Guinea Ecuatorial", "Republic of Equatorial Guinea",
                "Africa", "Middle Africa", "Africa", 1.6508m, 10.2679m,
                "+240", ".gq", "XAF", "Central African CFA Franc", "Fr",
                "es", "Spanish,French,Portuguese", "Malabo", "Equatorial Guinean",
                "Africa/Malabo", "🇬🇶", 1402985, 28051m),
            CreateCountry("ER", "ERI", "232", "Eritrea", "Ertra", "State of Eritrea",
                "Africa", "Eastern Africa", "Africa", 15.1794m, 39.7823m,
                "+291", ".er", "ERN", "Nakfa", "Nfk",
                "ti", "Tigrinya,Arabic,English", "Asmara", "Eritrean",
                "Africa/Asmara", "🇪🇷", 3546000, 117600m),
            CreateCountry("EE", "EST", "233", "Estonia", "Eesti", "Republic of Estonia",
                "Europe", "Northern Europe", "Europe", 58.5953m, 25.0136m,
                "+372", ".ee", "EUR", "Euro", "€",
                "et", "Estonian", "Tallinn", "Estonian",
                "Europe/Tallinn", "🇪🇪", 1328976, 45227m, true),
            CreateCountry("SZ", "SWZ", "748", "Eswatini", "Eswatini", "Kingdom of Eswatini",
                "Africa", "Southern Africa", "Africa", -26.5225m, 31.4659m,
                "+268", ".sz", "SZL", "Lilangeni", "L",
                "en", "English,Swazi", "Mbabane", "Swazi",
                "Africa/Mbabane", "🇸🇿", 1160164, 17364m),
            CreateCountry("ET", "ETH", "231", "Ethiopia", "Ethiopia", "Federal Democratic Republic of Ethiopia",
                "Africa", "Eastern Africa", "Africa", 9.1450m, 40.4897m,
                "+251", ".et", "ETB", "Ethiopian Birr", "Br",
                "am", "Amharic", "Addis Ababa", "Ethiopian",
                "Africa/Addis_Ababa", "🇪🇹", 114963583, 1104300m),
            CreateCountry("FJ", "FJI", "242", "Fiji", "Fiji", "Republic of Fiji",
                "Oceania", "Melanesia", "Oceania", -17.7134m, 178.0650m,
                "+679", ".fj", "FJD", "Fijian Dollar", "$",
                "en", "English,Fijian", "Suva", "Fijian",
                "Pacific/Fiji", "🇫🇯", 896444, 18274m),
            CreateCountry("FI", "FIN", "246", "Finland", "Suomi", "Republic of Finland",
                "Europe", "Northern Europe", "Europe", 61.9241m, 25.7482m,
                "+358", ".fi", "EUR", "Euro", "€",
                "fi", "Finnish,Swedish", "Helsinki", "Finnish",
                "Europe/Helsinki", "🇫🇮", 5530719, 338424m, true),
            CreateCountry("FR", "FRA", "250", "France", "France", "French Republic",
                "Europe", "Western Europe", "Europe", 46.2276m, 2.2137m,
                "+33", ".fr", "EUR", "Euro", "€",
                "fr", "French", "Paris", "French",
                "Europe/Paris", "🇫🇷", 65273511, 643801m, true),
            CreateCountry("GA", "GAB", "266", "Gabon", "Gabon", "Gabonese Republic",
                "Africa", "Middle Africa", "Africa", -0.8037m, 11.6094m,
                "+241", ".ga", "XAF", "Central African CFA Franc", "Fr",
                "fr", "French", "Libreville", "Gabonese",
                "Africa/Libreville", "🇬🇦", 2225728, 267668m),
            CreateCountry("GM", "GMB", "270", "Gambia", "Gambia", "Republic of the Gambia",
                "Africa", "Western Africa", "Africa", 13.4432m, -15.3101m,
                "+220", ".gm", "GMD", "Dalasi", "D",
                "en", "English", "Banjul", "Gambian",
                "Africa/Banjul", "🇬🇲", 2416664, 11295m),
            CreateCountry("GE", "GEO", "268", "Georgia", "Sakartvelo", "Georgia",
                "Asia", "Western Asia", "Asia", 42.3154m, 43.3569m,
                "+995", ".ge", "GEL", "Lari", "₾",
                "ka", "Georgian", "Tbilisi", "Georgian",
                "Asia/Tbilisi", "🇬🇪", 3989175, 69700m),
            CreateCountry("DE", "DEU", "276", "Germany", "Deutschland", "Federal Republic of Germany",
                "Europe", "Western Europe", "Europe", 51.1657m, 10.4515m,
                "+49", ".de", "EUR", "Euro", "€",
                "de", "German", "Berlin", "German",
                "Europe/Berlin", "🇩🇪", 83783942, 357114m, true),
            CreateCountry("GH", "GHA", "288", "Ghana", "Ghana", "Republic of Ghana",
                "Africa", "Western Africa", "Africa", 7.9465m, -1.0232m,
                "+233", ".gh", "GHS", "Ghanaian Cedi", "₵",
                "en", "English", "Accra", "Ghanaian",
                "Africa/Accra", "🇬🇭", 31072945, 238533m),
            CreateCountry("GR", "GRC", "300", "Greece", "Ελλάδα", "Hellenic Republic",
                "Europe", "Southern Europe", "Europe", 39.0742m, 21.8243m,
                "+30", ".gr", "EUR", "Euro", "€",
                "el", "Greek", "Athens", "Greek",
                "Europe/Athens", "🇬🇷", 10715549, 131990m, true),
            CreateCountry("GD", "GRD", "308", "Grenada", "Grenada", "Grenada",
                "Americas", "Caribbean", "North America", 12.1165m, -61.6790m,
                "+1-473", ".gd", "XCD", "East Caribbean Dollar", "$",
                "en", "English", "St. George's", "Grenadian",
                "America/Grenada", "🇬🇩", 112519, 344m),
            CreateCountry("GT", "GTM", "320", "Guatemala", "Guatemala", "Republic of Guatemala",
                "Americas", "Central America", "North America", 15.7835m, -90.2308m,
                "+502", ".gt", "GTQ", "Quetzal", "Q",
                "es", "Spanish", "Guatemala City", "Guatemalan",
                "America/Guatemala", "🇬🇹", 17915567, 108889m),
            CreateCountry("GN", "GIN", "324", "Guinea", "Guinée", "Republic of Guinea",
                "Africa", "Western Africa", "Africa", 9.9456m, -9.6966m,
                "+224", ".gn", "GNF", "Guinean Franc", "Fr",
                "fr", "French", "Conakry", "Guinean",
                "Africa/Conakry", "🇬🇳", 13132792, 245857m),
            CreateCountry("GW", "GNB", "624", "Guinea-Bissau", "Guiné-Bissau", "Republic of Guinea-Bissau",
                "Africa", "Western Africa", "Africa", 11.8037m, -15.1804m,
                "+245", ".gw", "XOF", "West African CFA Franc", "Fr",
                "pt", "Portuguese", "Bissau", "Bissau-Guinean",
                "Africa/Bissau", "🇬🇼", 1967998, 36125m),
            CreateCountry("GY", "GUY", "328", "Guyana", "Guyana", "Co-operative Republic of Guyana",
                "Americas", "South America", "South America", 4.8604m, -58.9302m,
                "+592", ".gy", "GYD", "Guyanese Dollar", "$",
                "en", "English", "Georgetown", "Guyanese",
                "America/Guyana", "🇬🇾", 786559, 214969m),
            CreateCountry("HT", "HTI", "332", "Haiti", "Haïti", "Republic of Haiti",
                "Americas", "Caribbean", "North America", 18.9712m, -72.2852m,
                "+509", ".ht", "HTG", "Gourde", "G",
                "fr", "French,Haitian Creole", "Port-au-Prince", "Haitian",
                "America/Port-au-Prince", "🇭🇹", 11402533, 27750m),
            CreateCountry("HN", "HND", "340", "Honduras", "Honduras", "Republic of Honduras",
                "Americas", "Central America", "North America", 15.2000m, -86.2419m,
                "+504", ".hn", "HNL", "Lempira", "L",
                "es", "Spanish", "Tegucigalpa", "Honduran",
                "America/Tegucigalpa", "🇭🇳", 9904608, 112492m),
            CreateCountry("HK", "HKG", "344", "Hong Kong", "香港", "Hong Kong SAR China",
                "Asia", "Eastern Asia", "Asia", 22.3193m, 114.1694m,
                "+852", ".hk", "HKD", "Hong Kong Dollar", "HK$",
                "zh", "Cantonese,English", "Hong Kong", "Hong Konger",
                "Asia/Hong_Kong", "🇭🇰", 7496981, 1104m),
            CreateCountry("HU", "HUN", "348", "Hungary", "Magyarország", "Hungary",
                "Europe", "Eastern Europe", "Europe", 47.1625m, 19.5033m,
                "+36", ".hu", "HUF", "Hungarian Forint", "Ft",
                "hu", "Hungarian", "Budapest", "Hungarian",
                "Europe/Budapest", "🇭🇺", 9660351, 93028m, true),
            CreateCountry("IS", "ISL", "352", "Iceland", "Ísland", "Iceland",
                "Europe", "Northern Europe", "Europe", 64.9631m, -19.0208m,
                "+354", ".is", "ISK", "Icelandic Króna", "kr",
                "is", "Icelandic", "Reykjavík", "Icelander",
                "Atlantic/Reykjavik", "🇮🇸", 366425, 103000m),
            CreateCountry("IN", "IND", "356", "India", "भारत", "Republic of India",
                "Asia", "Southern Asia", "Asia", 20.5937m, 78.9629m,
                "+91", ".in", "INR", "Indian Rupee", "₹",
                "hi", "Hindi,English", "New Delhi", "Indian",
                "Asia/Kolkata", "🇮🇳", 1380004385, 3287263m),
            CreateCountry("ID", "IDN", "360", "Indonesia", "Indonesia", "Republic of Indonesia",
                "Asia", "South-Eastern Asia", "Asia", -0.7893m, 113.9213m,
                "+62", ".id", "IDR", "Indonesian Rupiah", "Rp",
                "id", "Indonesian", "Jakarta", "Indonesian",
                "Asia/Jakarta", "🇮🇩", 273523615, 1904569m),
            CreateCountry("IR", "IRN", "364", "Iran", "Iran", "Islamic Republic of Iran",
                "Asia", "Southern Asia", "Asia", 32.4279m, 53.6880m,
                "+98", ".ir", "IRR", "Iranian Rial", "﷼",
                "fa", "Persian", "Tehran", "Iranian",
                "Asia/Tehran", "🇮🇷", 83992953, 1648195m),
            CreateCountry("IQ", "IRQ", "368", "Iraq", "Iraq", "Republic of Iraq",
                "Asia", "Western Asia", "Asia", 33.2232m, 43.6793m,
                "+964", ".iq", "IQD", "Iraqi Dinar", "ع.د",
                "ar", "Arabic,Kurdish", "Baghdad", "Iraqi",
                "Asia/Baghdad", "🇮🇶", 40222503, 438317m),
            CreateCountry("IE", "IRL", "372", "Ireland", "Éire", "Republic of Ireland",
                "Europe", "Northern Europe", "Europe", 53.1424m, -7.6921m,
                "+353", ".ie", "EUR", "Euro", "€",
                "en", "English,Irish", "Dublin", "Irish",
                "Europe/Dublin", "🇮🇪", 4994724, 70273m, true),
            CreateCountry("IL", "ISR", "376", "Israel", "יִשְׂרָאֵל", "State of Israel",
                "Asia", "Western Asia", "Asia", 31.0461m, 34.8516m,
                "+972", ".il", "ILS", "Israeli New Shekel", "₪",
                "he", "Hebrew,Arabic", "Jerusalem", "Israeli",
                "Asia/Jerusalem", "🇮🇱", 9216900, 20770m),
            CreateCountry("IT", "ITA", "380", "Italy", "Italia", "Italian Republic",
                "Europe", "Southern Europe", "Europe", 41.8719m, 12.5674m,
                "+39", ".it", "EUR", "Euro", "€",
                "it", "Italian", "Rome", "Italian",
                "Europe/Rome", "🇮🇹", 60461826, 301340m, true),
            CreateCountry("CI", "CIV", "384", "Ivory Coast", "Côte d'Ivoire", "Republic of Côte d'Ivoire",
                "Africa", "Western Africa", "Africa", 7.5400m, -5.5471m,
                "+225", ".ci", "XOF", "West African CFA Franc", "Fr",
                "fr", "French", "Yamoussoukro", "Ivorian",
                "Africa/Abidjan", "🇨🇮", 26378275, 322463m),
            CreateCountry("JM", "JAM", "388", "Jamaica", "Jamaica", "Jamaica",
                "Americas", "Caribbean", "North America", 18.1096m, -77.2975m,
                "+1-876", ".jm", "JMD", "Jamaican Dollar", "J$",
                "en", "English", "Kingston", "Jamaican",
                "America/Jamaica", "🇯🇲", 2961161, 10991m),
            CreateCountry("JP", "JPN", "392", "Japan", "日本", "Japan",
                "Asia", "Eastern Asia", "Asia", 36.2048m, 138.2529m,
                "+81", ".jp", "JPY", "Japanese Yen", "¥",
                "ja", "Japanese", "Tokyo", "Japanese",
                "Asia/Tokyo", "🇯🇵", 126476461, 377975m),
            CreateCountry("JO", "JOR", "400", "Jordan", "Al-Urdun", "Hashemite Kingdom of Jordan",
                "Asia", "Western Asia", "Asia", 30.5852m, 36.2384m,
                "+962", ".jo", "JOD", "Jordanian Dinar", "د.ا",
                "ar", "Arabic", "Amman", "Jordanian",
                "Asia/Amman", "🇯🇴", 10203140, 89342m),
            CreateCountry("KZ", "KAZ", "398", "Kazakhstan", "Qazaqstan", "Republic of Kazakhstan",
                "Asia", "Central Asia", "Asia", 48.0196m, 66.9237m,
                "+7", ".kz", "KZT", "Kazakhstani Tenge", "₸",
                "kk", "Kazakh,Russian", "Astana", "Kazakhstani",
                "Asia/Almaty", "🇰🇿", 18776707, 2724900m),
            CreateCountry("KE", "KEN", "404", "Kenya", "Kenya", "Republic of Kenya",
                "Africa", "Eastern Africa", "Africa", -0.0236m, 37.9062m,
                "+254", ".ke", "KES", "Kenyan Shilling", "KSh",
                "sw", "Swahili,English", "Nairobi", "Kenyan",
                "Africa/Nairobi", "🇰🇪", 53771300, 580367m),
            CreateCountry("KI", "KIR", "296", "Kiribati", "Kiribati", "Independent and Sovereign Republic of Kiribati",
                "Oceania", "Micronesia", "Oceania", 1.8369m, -157.2765m,
                "+686", ".ki", "AUD", "Australian Dollar", "$",
                "en", "English,Gilbertese", "Tarawa", "I-Kiribati",
                "Pacific/Tarawa", "🇰🇮", 119446, 811m),
            CreateCountry("KW", "KWT", "414", "Kuwait", "Kuwait", "State of Kuwait",
                "Asia", "Western Asia", "Asia", 29.3117m, 47.4818m,
                "+965", ".kw", "KWD", "Kuwaiti Dinar", "د.ك",
                "ar", "Arabic", "Kuwait City", "Kuwaiti",
                "Asia/Kuwait", "🇰🇼", 4270563, 17818m),
            CreateCountry("KG", "KGZ", "417", "Kyrgyzstan", "Kyrgyzstan", "Kyrgyz Republic",
                "Asia", "Central Asia", "Asia", 41.2044m, 74.7661m,
                "+996", ".kg", "KGS", "Kyrgyzstani Som", "с",
                "ky", "Kyrgyz,Russian", "Bishkek", "Kyrgyzstani",
                "Asia/Bishkek", "🇰🇬", 6524191, 199951m),
            CreateCountry("LA", "LAO", "418", "Laos", "ລາວ", "Lao People's Democratic Republic",
                "Asia", "South-Eastern Asia", "Asia", 19.8563m, 102.4955m,
                "+856", ".la", "LAK", "Lao Kip", "₭",
                "lo", "Lao", "Vientiane", "Laotian",
                "Asia/Vientiane", "🇱🇦", 7275560, 236800m),
            CreateCountry("LV", "LVA", "428", "Latvia", "Latvija", "Republic of Latvia",
                "Europe", "Northern Europe", "Europe", 56.8796m, 24.6032m,
                "+371", ".lv", "EUR", "Euro", "€",
                "lv", "Latvian", "Riga", "Latvian",
                "Europe/Riga", "🇱🇻", 1907675, 64559m, true),
            CreateCountry("LB", "LBN", "422", "Lebanon", "Lubnān", "Lebanese Republic",
                "Asia", "Western Asia", "Asia", 33.8547m, 35.8623m,
                "+961", ".lb", "LBP", "Lebanese Pound", "ل.ل",
                "ar", "Arabic", "Beirut", "Lebanese",
                "Asia/Beirut", "🇱🇧", 6825442, 10452m),
            CreateCountry("LS", "LSO", "426", "Lesotho", "Lesotho", "Kingdom of Lesotho",
                "Africa", "Southern Africa", "Africa", -29.6099m, 28.2336m,
                "+266", ".ls", "LSL", "Loti", "L",
                "en", "English,Sotho", "Maseru", "Basotho",
                "Africa/Maseru", "🇱🇸", 2142252, 30355m),
            CreateCountry("LR", "LBR", "430", "Liberia", "Liberia", "Republic of Liberia",
                "Africa", "Western Africa", "Africa", 6.4281m, -9.4295m,
                "+231", ".lr", "LRD", "Liberian Dollar", "$",
                "en", "English", "Monrovia", "Liberian",
                "Africa/Monrovia", "🇱🇷", 5057677, 111369m),
            CreateCountry("LY", "LBY", "434", "Libya", "Libya", "State of Libya",
                "Africa", "Northern Africa", "Africa", 26.3351m, 17.2283m,
                "+218", ".ly", "LYD", "Libyan Dinar", "ل.د",
                "ar", "Arabic", "Tripoli", "Libyan",
                "Africa/Tripoli", "🇱🇾", 6871287, 1759540m),
            CreateCountry("LI", "LIE", "438", "Liechtenstein", "Liechtenstein", "Principality of Liechtenstein",
                "Europe", "Western Europe", "Europe", 47.1660m, 9.5554m,
                "+423", ".li", "CHF", "Swiss Franc", "Fr",
                "de", "German", "Vaduz", "Liechtensteiner",
                "Europe/Vaduz", "🇱🇮", 38137, 160m),
            CreateCountry("LT", "LTU", "440", "Lithuania", "Lietuva", "Republic of Lithuania",
                "Europe", "Northern Europe", "Europe", 55.1694m, 23.8813m,
                "+370", ".lt", "EUR", "Euro", "€",
                "lt", "Lithuanian", "Vilnius", "Lithuanian",
                "Europe/Vilnius", "🇱🇹", 2794090, 65300m, true),
            CreateCountry("LU", "LUX", "442", "Luxembourg", "Luxembourg", "Grand Duchy of Luxembourg",
                "Europe", "Western Europe", "Europe", 49.8153m, 6.1296m,
                "+352", ".lu", "EUR", "Euro", "€",
                "lb", "Luxembourgish,French,German", "Luxembourg", "Luxembourger",
                "Europe/Luxembourg", "🇱🇺", 632275, 2586m, true),
            CreateCountry("MG", "MDG", "450", "Madagascar", "Madagasikara", "Republic of Madagascar",
                "Africa", "Eastern Africa", "Africa", -18.7669m, 46.8691m,
                "+261", ".mg", "MGA", "Malagasy Ariary", "Ar",
                "mg", "Malagasy,French", "Antananarivo", "Malagasy",
                "Indian/Antananarivo", "🇲🇬", 27691019, 587041m),
            CreateCountry("MW", "MWI", "454", "Malawi", "Malawi", "Republic of Malawi",
                "Africa", "Eastern Africa", "Africa", -13.2543m, 34.3015m,
                "+265", ".mw", "MWK", "Malawian Kwacha", "MK",
                "en", "English,Chewa", "Lilongwe", "Malawian",
                "Africa/Blantyre", "🇲🇼", 19129955, 118484m),
            CreateCountry("MY", "MYS", "458", "Malaysia", "Malaysia", "Malaysia",
                "Asia", "South-Eastern Asia", "Asia", 4.2105m, 101.9758m,
                "+60", ".my", "MYR", "Malaysian Ringgit", "RM",
                "ms", "Malay,English,Mandarin,Tamil", "Kuala Lumpur", "Malaysian",
                "Asia/Kuala_Lumpur", "🇲🇾", 32365999, 330803m),
            CreateCountry("MV", "MDV", "462", "Maldives", "Dhivehi Raajje", "Republic of Maldives",
                "Asia", "Southern Asia", "Asia", 3.2028m, 73.2207m,
                "+960", ".mv", "MVR", "Rufiyaa", ".ރ",
                "dv", "Dhivehi", "Malé", "Maldivian",
                "Indian/Maldives", "🇲🇻", 540542, 300m),
            CreateCountry("ML", "MLI", "466", "Mali", "Mali", "Republic of Mali",
                "Africa", "Western Africa", "Africa", 17.5707m, -3.9962m,
                "+223", ".ml", "XOF", "West African CFA Franc", "Fr",
                "fr", "French", "Bamako", "Malian",
                "Africa/Bamako", "🇲🇱", 20250834, 1240192m),
            CreateCountry("MT", "MLT", "470", "Malta", "Malta", "Republic of Malta",
                "Europe", "Southern Europe", "Europe", 35.9375m, 14.3754m,
                "+356", ".mt", "EUR", "Euro", "€",
                "mt", "Maltese,English", "Valletta", "Maltese",
                "Europe/Malta", "🇲🇹", 525285, 316m, true),
            CreateCountry("MH", "MHL", "584", "Marshall Islands", "Marshall Islands",
                "Republic of the Marshall Islands",
                "Oceania", "Micronesia", "Oceania", 7.1315m, 171.1845m,
                "+692", ".mh", "USD", "US Dollar", "$",
                "en", "English,Marshallese", "Majuro", "Marshallese",
                "Pacific/Majuro", "🇲🇭", 59194, 181m),
            CreateCountry("MR", "MRT", "478", "Mauritania", "Mauritanie", "Islamic Republic of Mauritania",
                "Africa", "Western Africa", "Africa", 21.0079m, -10.9408m,
                "+222", ".mr", "MRU", "Ouguiya", "UM",
                "ar", "Arabic", "Nouakchott", "Mauritanian",
                "Africa/Nouakchott", "🇲🇷", 4649660, 1030700m),
            CreateCountry("MU", "MUS", "480", "Mauritius", "Mauritius", "Republic of Mauritius",
                "Africa", "Eastern Africa", "Africa", -20.3484m, 57.5522m,
                "+230", ".mu", "MUR", "Mauritian Rupee", "₨",
                "en", "English,French", "Port Louis", "Mauritian",
                "Indian/Mauritius", "🇲🇺", 1265740, 2040m),
            CreateCountry("MX", "MEX", "484", "Mexico", "México", "United Mexican States",
                "Americas", "Central America", "North America", 23.6345m, -102.5528m,
                "+52", ".mx", "MXN", "Mexican Peso", "$",
                "es", "Spanish", "Mexico City", "Mexican",
                "America/Mexico_City", "🇲🇽", 128932753, 1964375m),
            CreateCountry("FM", "FSM", "583", "Micronesia", "Micronesia", "Federated States of Micronesia",
                "Oceania", "Micronesia", "Oceania", 7.4256m, 150.5508m,
                "+691", ".fm", "USD", "US Dollar", "$",
                "en", "English", "Palikir", "Micronesian",
                "Pacific/Pohnpei", "🇫🇲", 115021, 702m),
            CreateCountry("MD", "MDA", "498", "Moldova", "Moldova", "Republic of Moldova",
                "Europe", "Eastern Europe", "Europe", 47.4116m, 28.3699m,
                "+373", ".md", "MDL", "Moldovan Leu", "L",
                "ro", "Romanian", "Chișinău", "Moldovan",
                "Europe/Chisinau", "🇲🇩", 2640438, 33846m),
            CreateCountry("MC", "MCO", "492", "Monaco", "Monaco", "Principality of Monaco",
                "Europe", "Western Europe", "Europe", 43.7384m, 7.4246m,
                "+377", ".mc", "EUR", "Euro", "€",
                "fr", "French", "Monaco", "Monegasque",
                "Europe/Monaco", "🇲🇨", 39244, 2m),
            CreateCountry("MN", "MNG", "496", "Mongolia", "Mongol Uls", "Mongolia",
                "Asia", "Eastern Asia", "Asia", 46.8625m, 103.8467m,
                "+976", ".mn", "MNT", "Tögrög", "₮",
                "mn", "Mongolian", "Ulaanbaatar", "Mongolian",
                "Asia/Ulaanbaatar", "🇲🇳", 3278292, 1564110m),
            CreateCountry("ME", "MNE", "499", "Montenegro", "Crna Gora", "Montenegro",
                "Europe", "Southern Europe", "Europe", 42.7087m, 19.3744m,
                "+382", ".me", "EUR", "Euro", "€",
                "sr", "Montenegrin", "Podgorica", "Montenegrin",
                "Europe/Podgorica", "🇲🇪", 621718, 13812m),
            CreateCountry("MA", "MAR", "504", "Morocco", "Maroc", "Kingdom of Morocco",
                "Africa", "Northern Africa", "Africa", 31.7917m, -7.0926m,
                "+212", ".ma", "MAD", "Moroccan Dirham", "د.م.",
                "ar", "Arabic,Berber", "Rabat", "Moroccan",
                "Africa/Casablanca", "🇲🇦", 36910558, 446550m),
            CreateCountry("MZ", "MOZ", "508", "Mozambique", "Moçambique", "Republic of Mozambique",
                "Africa", "Eastern Africa", "Africa", -18.6657m, 35.5296m,
                "+258", ".mz", "MZN", "Mozambican Metical", "MT",
                "pt", "Portuguese", "Maputo", "Mozambican",
                "Africa/Maputo", "🇲🇿", 31255435, 801590m),
            CreateCountry("MM", "MMR", "104", "Myanmar", "မြန်မာ", "Republic of the Union of Myanmar",
                "Asia", "South-Eastern Asia", "Asia", 21.9162m, 95.9560m,
                "+95", ".mm", "MMK", "Myanmar Kyat", "K",
                "my", "Burmese", "Naypyidaw", "Burmese",
                "Asia/Yangon", "🇲🇲", 54409800, 676578m),
            CreateCountry("NA", "NAM", "516", "Namibia", "Namibia", "Republic of Namibia",
                "Africa", "Southern Africa", "Africa", -22.9576m, 18.4904m,
                "+264", ".na", "NAD", "Namibian Dollar", "$",
                "en", "English", "Windhoek", "Namibian",
                "Africa/Windhoek", "🇳🇦", 2540916, 825615m),
            CreateCountry("NR", "NRU", "520", "Nauru", "Nauru", "Republic of Nauru",
                "Oceania", "Micronesia", "Oceania", -0.5228m, 166.9315m,
                "+674", ".nr", "AUD", "Australian Dollar", "$",
                "en", "English,Nauruan", "Yaren", "Nauruan",
                "Pacific/Nauru", "🇳🇷", 10834, 21m),
            CreateCountry("NP", "NPL", "524", "Nepal", "Nepal", "Federal Democratic Republic of Nepal",
                "Asia", "Southern Asia", "Asia", 28.3949m, 84.1240m,
                "+977", ".np", "NPR", "Nepalese Rupee", "Rs",
                "ne", "Nepali", "Kathmandu", "Nepalese",
                "Asia/Kathmandu", "🇳🇵", 29136808, 147181m),
            CreateCountry("NL", "NLD", "528", "Netherlands", "Nederland", "Kingdom of the Netherlands",
                "Europe", "Western Europe", "Europe", 52.1326m, 5.2913m,
                "+31", ".nl", "EUR", "Euro", "€",
                "nl", "Dutch", "Amsterdam", "Dutch",
                "Europe/Amsterdam", "🇳🇱", 17134872, 41850m, true),
            CreateCountry("NZ", "NZL", "554", "New Zealand", "New Zealand", "New Zealand",
                "Oceania", "Australia and New Zealand", "Oceania", -40.9006m, 174.8860m,
                "+64", ".nz", "NZD", "New Zealand Dollar", "$",
                "en", "English,Maori", "Wellington", "New Zealander",
                "Pacific/Auckland", "🇳🇿", 4822233, 270467m),
            CreateCountry("NI", "NIC", "558", "Nicaragua", "Nicaragua", "Republic of Nicaragua",
                "Americas", "Central America", "North America", 12.8654m, -85.2072m,
                "+505", ".ni", "NIO", "Córdoba", "C$",
                "es", "Spanish", "Managua", "Nicaraguan",
                "America/Managua", "🇳🇮", 6624554, 130373m),
            CreateCountry("NE", "NER", "562", "Niger", "Niger", "Republic of the Niger",
                "Africa", "Western Africa", "Africa", 17.6078m, 8.0817m,
                "+227", ".ne", "XOF", "West African CFA Franc", "Fr",
                "fr", "French", "Niamey", "Nigerien",
                "Africa/Niamey", "🇳🇪", 24206636, 1267000m),
            CreateCountry("NG", "NGA", "566", "Nigeria", "Nigeria", "Federal Republic of Nigeria",
                "Africa", "Western Africa", "Africa", 9.0820m, 8.6753m,
                "+234", ".ng", "NGN", "Nigerian Naira", "₦",
                "en", "English", "Abuja", "Nigerian",
                "Africa/Lagos", "🇳🇬", 206139589, 923768m),
            CreateCountry("MK", "MKD", "807", "North Macedonia", "Северна Македонија", "Republic of North Macedonia",
                "Europe", "Southern Europe", "Europe", 41.6086m, 21.7453m,
                "+389", ".mk", "MKD", "Denar", "ден",
                "mk", "Macedonian", "Skopje", "Macedonian",
                "Europe/Skopje", "🇲🇰", 2072531, 25713m),
            CreateCountry("NO", "NOR", "578", "Norway", "Norge", "Kingdom of Norway",
                "Europe", "Northern Europe", "Europe", 60.4720m, 8.4689m,
                "+47", ".no", "NOK", "Norwegian Krone", "kr",
                "no", "Norwegian", "Oslo", "Norwegian",
                "Europe/Oslo", "🇳🇴", 5421241, 385207m, false),
            CreateCountry("OM", "OMN", "512", "Oman", "Oman", "Sultanate of Oman",
                "Asia", "Western Asia", "Asia", 21.4735m, 55.9754m,
                "+968", ".om", "OMR", "Omani Rial", "ر.ع.",
                "ar", "Arabic", "Muscat", "Omani",
                "Asia/Muscat", "🇴🇲", 5106622, 309500m),
            CreateCountry("PK", "PAK", "586", "Pakistan", "Pakistan", "Islamic Republic of Pakistan",
                "Asia", "Southern Asia", "Asia", 30.3753m, 69.3451m,
                "+92", ".pk", "PKR", "Pakistani Rupee", "₨",
                "ur", "Urdu,English", "Islamabad", "Pakistani",
                "Asia/Karachi", "🇵🇰", 220892340, 881913m),
            CreateCountry("PW", "PLW", "585", "Palau", "Palau", "Republic of Palau",
                "Oceania", "Micronesia", "Oceania", 7.5150m, 134.5825m,
                "+680", ".pw", "USD", "US Dollar", "$",
                "en", "English,Palauan", "Ngerulmud", "Palauan",
                "Pacific/Palau", "🇵🇼", 18092, 459m),
            CreateCountry("PA", "PAN", "591", "Panama", "Panamá", "Republic of Panama",
                "Americas", "Central America", "North America", 8.5380m, -80.7821m,
                "+507", ".pa", "PAB", "Balboa", "B/.",
                "es", "Spanish", "Panama City", "Panamanian",
                "America/Panama", "🇵🇦", 4314768, 75417m),
            CreateCountry("PG", "PNG", "598", "Papua New Guinea", "Papua New Guinea",
                "Independent State of Papua New Guinea",
                "Oceania", "Melanesia", "Oceania", -6.314993m, 143.95555m,
                "+675", ".pg", "PGK", "Kina", "K",
                "en", "English,Tok Pisin,Hiri Motu", "Port Moresby", "Papua New Guinean",
                "Pacific/Port_Moresby", "🇵🇬", 8947027, 462840m),
            CreateCountry("PY", "PRY", "600", "Paraguay", "Paraguay", "Republic of Paraguay",
                "Americas", "South America", "South America", -23.4425m, -58.4438m,
                "+595", ".py", "PYG", "Guaraní", "₲",
                "es", "Spanish,Guaraní", "Asunción", "Paraguayan",
                "America/Asuncion", "🇵🇾", 7132530, 406752m),
            CreateCountry("PE", "PER", "604", "Peru", "Perú", "Republic of Peru",
                "Americas", "South America", "South America", -9.1900m, -75.0152m,
                "+51", ".pe", "PEN", "Sol", "S/",
                "es", "Spanish", "Lima", "Peruvian",
                "America/Lima", "🇵🇪", 32971846, 1285216m),
            CreateCountry("PH", "PHL", "608", "Philippines", "Pilipinas", "Republic of the Philippines",
                "Asia", "South-Eastern Asia", "Asia", 12.8797m, 121.7740m,
                "+63", ".ph", "PHP", "Philippine Peso", "₱",
                "en", "Filipino,English", "Manila", "Filipino",
                "Asia/Manila", "🇵🇭", 109581078, 342353m),
            CreateCountry("PL", "POL", "616", "Poland", "Polska", "Republic of Poland",
                "Europe", "Eastern Europe", "Europe", 51.9194m, 19.1451m,
                "+48", ".pl", "PLN", "Polish Złoty", "zł",
                "pl", "Polish", "Warsaw", "Polish",
                "Europe/Warsaw", "🇵🇱", 37846611, 312696m, true),
            CreateCountry("PT", "PRT", "620", "Portugal", "Portugal", "Portuguese Republic",
                "Europe", "Southern Europe", "Europe", 39.3999m, -8.2245m,
                "+351", ".pt", "EUR", "Euro", "€",
                "pt", "Portuguese", "Lisbon", "Portuguese",
                "Europe/Lisbon", "🇵🇹", 10196709, 92090m, true),
            CreateCountry("QA", "QAT", "634", "Qatar", "Qatar", "State of Qatar",
                "Asia", "Western Asia", "Asia", 25.3548m, 51.1839m,
                "+974", ".qa", "QAR", "Qatari Riyal", "ر.ق",
                "ar", "Arabic", "Doha", "Qatari",
                "Asia/Qatar", "🇶🇦", 2881060, 11586m),
            CreateCountry("RO", "ROU", "642", "Romania", "România", "Romania",
                "Europe", "Eastern Europe", "Europe", 45.9432m, 24.9668m,
                "+40", ".ro", "RON", "Romanian Leu", "lei",
                "ro", "Romanian", "Bucharest", "Romanian",
                "Europe/Bucharest", "🇷🇴", 19286123, 238391m, true),
            CreateCountry("RU", "RUS", "643", "Russia", "Россия", "Russian Federation",
                "Europe", "Eastern Europe", "Europe", 61.5240m, 105.3188m,
                "+7", ".ru", "RUB", "Russian Ruble", "₽",
                "ru", "Russian", "Moscow", "Russian",
                "Europe/Moscow", "🇷🇺", 145934462, 17098242m, false),
            CreateCountry("RW", "RWA", "646", "Rwanda", "Rwanda", "Republic of Rwanda",
                "Africa", "Eastern Africa", "Africa", -1.9403m, 29.8739m,
                "+250", ".rw", "RWF", "Rwandan Franc", "Fr",
                "rw", "Kinyarwanda,English,French", "Kigali", "Rwandan",
                "Africa/Kigali", "🇷🇼", 12952209, 26338m),
            CreateCountry("KN", "KNA", "659", "Saint Kitts and Nevis", "Saint Kitts and Nevis",
                "Federation of Saint Kitts and Nevis",
                "Americas", "Caribbean", "North America", 17.3578m, -62.7830m,
                "+1-869", ".kn", "XCD", "East Caribbean Dollar", "$",
                "en", "English", "Basseterre", "Kittitian",
                "America/St_Kitts", "🇰🇳", 53192, 261m),
            CreateCountry("LC", "LCA", "662", "Saint Lucia", "Saint Lucia", "Saint Lucia",
                "Americas", "Caribbean", "North America", 13.9094m, -60.9789m,
                "+1-758", ".lc", "XCD", "East Caribbean Dollar", "$",
                "en", "English", "Castries", "Saint Lucian",
                "America/St_Lucia", "🇱🇨", 183629, 616m),
            CreateCountry("VC", "VCT", "670", "Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines",
                "Saint Vincent and the Grenadines",
                "Americas", "Caribbean", "North America", 12.9843m, -61.2872m,
                "+1-784", ".vc", "XCD", "East Caribbean Dollar", "$",
                "en", "English", "Kingstown", "Vincentian",
                "America/St_Vincent", "🇻🇨", 110947, 389m),
            CreateCountry("WS", "WSM", "882", "Samoa", "Samoa", "Independent State of Samoa",
                "Oceania", "Polynesia", "Oceania", -13.7590m, -172.1046m,
                "+685", ".ws", "WST", "Tala", "T",
                "sm", "Samoan,English", "Apia", "Samoan",
                "Pacific/Apia", "🇼🇸", 198410, 2842m),
            CreateCountry("SM", "SMR", "674", "San Marino", "San Marino", "Republic of San Marino",
                "Europe", "Southern Europe", "Europe", 43.9424m, 12.4578m,
                "+378", ".sm", "EUR", "Euro", "€",
                "it", "Italian", "San Marino", "Sammarinese",
                "Europe/San_Marino", "🇸🇲", 33938, 61m),
            CreateCountry("ST", "STP", "678", "São Tomé and Príncipe", "São Tomé e Príncipe",
                "Democratic Republic of São Tomé and Príncipe",
                "Africa", "Middle Africa", "Africa", 0.1864m, 6.6131m,
                "+239", ".st", "STN", "Dobra", "Db",
                "pt", "Portuguese", "São Tomé", "São Toméan",
                "Africa/Sao_Tome", "🇸🇹", 219161, 964m),
            CreateCountry("SA", "SAU", "682", "Saudi Arabia", "المملكة العربية السعودية", "Kingdom of Saudi Arabia",
                "Asia", "Western Asia", "Asia", 23.8859m, 45.0792m,
                "+966", ".sa", "SAR", "Saudi Riyal", "﷼",
                "ar", "Arabic", "Riyadh", "Saudi",
                "Asia/Riyadh", "🇸🇦", 34813871, 2149690m),
            CreateCountry("SN", "SEN", "686", "Senegal", "Sénégal", "Republic of Senegal",
                "Africa", "Western Africa", "Africa", 14.4974m, -14.4524m,
                "+221", ".sn", "XOF", "West African CFA Franc", "Fr",
                "fr", "French,Wolof", "Dakar", "Senegalese",
                "Africa/Dakar", "🇸🇳", 16743930, 196722m),
            CreateCountry("RS", "SRB", "688", "Serbia", "Srbija", "Republic of Serbia",
                "Europe", "Southern Europe", "Europe", 44.0165m, 21.0059m,
                "+381", ".rs", "RSD", "Serbian Dinar", "дин.",
                "sr", "Serbian", "Belgrade", "Serbian",
                "Europe/Belgrade", "🇷🇸", 6908224, 88361m),
            CreateCountry("SC", "SYC", "690", "Seychelles", "Seychelles", "Republic of Seychelles",
                "Africa", "Eastern Africa", "Africa", -4.6796m, 55.4920m,
                "+248", ".sc", "SCR", "Seychellois Rupee", "₨",
                "fr", "French,English,Seychellois Creole", "Victoria", "Seychellois",
                "Indian/Mahe", "🇸🇨", 98462, 452m),
            CreateCountry("SL", "SLE", "694", "Sierra Leone", "Sierra Leone", "Republic of Sierra Leone",
                "Africa", "Western Africa", "Africa", 8.4606m, -11.7799m,
                "+232", ".sl", "SLL", "Leone", "Le",
                "en", "English", "Freetown", "Sierra Leonean",
                "Africa/Freetown", "🇸🇱", 7976985, 71740m),
            CreateCountry("SG", "SGP", "702", "Singapore", "Singapore", "Republic of Singapore",
                "Asia", "South-Eastern Asia", "Asia", 1.3521m, 103.8198m,
                "+65", ".sg", "SGD", "Singapore Dollar", "$",
                "en", "English,Mandarin,Malay,Tamil", "Singapore", "Singaporean",
                "Asia/Singapore", "🇸🇬", 5850342, 728.6m),
            CreateCountry("SK", "SVK", "703", "Slovakia", "Slovensko", "Slovak Republic",
                "Europe", "Eastern Europe", "Europe", 48.6690m, 19.6990m,
                "+421", ".sk", "EUR", "Euro", "€",
                "sk", "Slovak", "Bratislava", "Slovak",
                "Europe/Bratislava", "🇸🇰", 5458827, 49035m, true),
            CreateCountry("SI", "SVN", "705", "Slovenia", "Slovenija", "Republic of Slovenia",
                "Europe", "Southern Europe", "Europe", 46.1512m, 14.9955m,
                "+386", ".si", "EUR", "Euro", "€",
                "sl", "Slovene", "Ljubljana", "Slovenian",
                "Europe/Ljubljana", "🇸🇮", 2080908, 20273m, true),
            CreateCountry("SB", "SLB", "090", "Solomon Islands", "Solomon Islands", "Solomon Islands",
                "Oceania", "Melanesia", "Oceania", -9.6457m, 160.1562m,
                "+677", ".sb", "SBD", "Solomon Islands Dollar", "$",
                "en", "English", "Honiara", "Solomon Islander",
                "Pacific/Guadalcanal", "🇸🇧", 686878, 28896m),
            CreateCountry("SO", "SOM", "706", "Somalia", "Somalia", "Federal Republic of Somalia",
                "Africa", "Eastern Africa", "Africa", 5.1521m, 46.1996m,
                "+252", ".so", "SOS", "Somali Shilling", "Sh",
                "so", "Somali,Arabic", "Mogadishu", "Somali",
                "Africa/Mogadishu", "🇸🇴", 15893219, 637657m),
            CreateCountry("ZA", "ZAF", "710", "South Africa", "South Africa", "Republic of South Africa",
                "Africa", "Southern Africa", "Africa", -30.5595m, 22.9375m,
                "+27", ".za", "ZAR", "South African Rand", "R",
                "en", "English,Zulu,Xhosa,Afrikaans", "Pretoria", "South African",
                "Africa/Johannesburg", "🇿🇦", 59308690, 1221037m),
            CreateCountry("KR", "KOR", "410", "South Korea", "대한민국", "Republic of Korea",
                "Asia", "Eastern Asia", "Asia", 35.9078m, 127.7669m,
                "+82", ".kr", "KRW", "South Korean Won", "₩",
                "ko", "Korean", "Seoul", "South Korean",
                "Asia/Seoul", "🇰🇷", 51269185, 100339m),
            CreateCountry("SS", "SSD", "728", "South Sudan", "South Sudan", "Republic of South Sudan",
                "Africa", "Eastern Africa", "Africa", 6.8770m, 31.3070m,
                "+211", ".ss", "SSP", "South Sudanese Pound", "£",
                "en", "English", "Juba", "South Sudanese",
                "Africa/Juba", "🇸🇸", 11193729, 619745m),
            CreateCountry("ES", "ESP", "724", "Spain", "España", "Kingdom of Spain",
                "Europe", "Southern Europe", "Europe", 40.4637m, -3.7492m,
                "+34", ".es", "EUR", "Euro", "€",
                "es", "Spanish", "Madrid", "Spanish",
                "Europe/Madrid", "🇪🇸", 46754778, 505992m, true),
            CreateCountry("LK", "LKA", "144", "Sri Lanka", "Sri Lanka", "Democratic Socialist Republic of Sri Lanka",
                "Asia", "Southern Asia", "Asia", 7.8731m, 80.7718m,
                "+94", ".lk", "LKR", "Sri Lankan Rupee", "Rs",
                "si", "Sinhala,Tamil", "Colombo", "Sri Lankan",
                "Asia/Colombo", "🇱🇰", 21413250, 65610m),
            CreateCountry("SD", "SDN", "729", "Sudan", "Sudan", "Republic of the Sudan",
                "Africa", "Northern Africa", "Africa", 12.8628m, 30.2176m,
                "+249", ".sd", "SDG", "Sudanese Pound", "ج.س.",
                "ar", "Arabic,English", "Khartoum", "Sudanese",
                "Africa/Khartoum", "🇸🇩", 43849269, 1886068m),
            CreateCountry("SR", "SUR", "740", "Suriname", "Suriname", "Republic of Suriname",
                "Americas", "South America", "South America", 3.9193m, -56.0278m,
                "+597", ".sr", "SRD", "Suriname Dollar", "$",
                "nl", "Dutch", "Paramaribo", "Surinamese",
                "America/Paramaribo", "🇸🇷", 586634, 163820m),
            CreateCountry("SE", "SWE", "752", "Sweden", "Sverige", "Kingdom of Sweden",
                "Europe", "Northern Europe", "Europe", 60.1282m, 18.6435m,
                "+46", ".se", "SEK", "Swedish Krona", "kr",
                "sv", "Swedish", "Stockholm", "Swedish",
                "Europe/Stockholm", "🇸🇪", 10353442, 450295m, true),
            CreateCountry("CH", "CHE", "756", "Switzerland", "Schweiz", "Swiss Confederation",
                "Europe", "Western Europe", "Europe", 46.8182m, 8.2275m,
                "+41", ".ch", "CHF", "Swiss Franc", "Fr.",
                "de", "German,French,Italian", "Bern", "Swiss",
                "Europe/Zurich", "🇨🇭", 8654622, 41284m, false),
            CreateCountry("SY", "SYR", "760", "Syria", "Suriyah", "Syrian Arab Republic",
                "Asia", "Western Asia", "Asia", 34.8021m, 38.9968m,
                "+963", ".sy", "SYP", "Syrian Pound", "£",
                "ar", "Arabic", "Damascus", "Syrian",
                "Asia/Damascus", "🇸🇾", 17500657, 185180m),
            CreateCountry("TW", "TWN", "158", "Taiwan", "臺灣", "Republic of China",
                "Asia", "Eastern Asia", "Asia", 23.6978m, 120.9605m,
                "+886", ".tw", "TWD", "New Taiwan Dollar", "NT$",
                "zh", "Mandarin", "Taipei", "Taiwanese",
                "Asia/Taipei", "🇹🇼", 23816775, 36193m),
            CreateCountry("TJ", "TJK", "762", "Tajikistan", "Tojikiston", "Republic of Tajikistan",
                "Asia", "Central Asia", "Asia", 38.8610m, 71.2761m,
                "+992", ".tj", "TJS", "Somoni", "ЅМ",
                "tg", "Tajik", "Dushanbe", "Tajikistani",
                "Asia/Dushanbe", "🇹🇯", 9537642, 143100m),
            CreateCountry("TZ", "TZA", "834", "Tanzania", "Tanzania", "United Republic of Tanzania",
                "Africa", "Eastern Africa", "Africa", -6.3690m, 34.8888m,
                "+255", ".tz", "TZS", "Tanzanian Shilling", "Sh",
                "sw", "Swahili,English", "Dodoma", "Tanzanian",
                "Africa/Dar_es_Salaam", "🇹🇿", 59734213, 945087m),
            CreateCountry("TH", "THA", "764", "Thailand", "ประเทศไทย", "Kingdom of Thailand",
                "Asia", "South-Eastern Asia", "Asia", 15.8700m, 100.9925m,
                "+66", ".th", "THB", "Thai Baht", "฿",
                "th", "Thai", "Bangkok", "Thai",
                "Asia/Bangkok", "🇹🇭", 69799978, 513120m),
            CreateCountry("TL", "TLS", "626", "Timor-Leste", "Timor-Leste", "Democratic Republic of Timor-Leste",
                "Asia", "South-Eastern Asia", "Asia", -8.8742m, 125.7275m,
                "+670", ".tl", "USD", "US Dollar", "$",
                "pt", "Tetum,Portuguese", "Dili", "Timorese",
                "Asia/Dili", "🇹🇱", 1318442, 14874m),
            CreateCountry("TG", "TGO", "768", "Togo", "Togo", "Togolese Republic",
                "Africa", "Western Africa", "Africa", 8.6195m, 0.8248m,
                "+228", ".tg", "XOF", "West African CFA Franc", "Fr",
                "fr", "French", "Lomé", "Togolese",
                "Africa/Lome", "🇹🇬", 8278737, 56785m),
            CreateCountry("TO", "TON", "776", "Tonga", "Tonga", "Kingdom of Tonga",
                "Oceania", "Polynesia", "Oceania", -21.1790m, -175.1982m,
                "+676", ".to", "TOP", "Paʻanga", "T$",
                "to", "Tongan,English", "Nuku'alofa", "Tongan",
                "Pacific/Tongatapu", "🇹🇴", 105697, 747m),
            CreateCountry("TT", "TTO", "780", "Trinidad and Tobago", "Trinidad and Tobago",
                "Republic of Trinidad and Tobago",
                "Americas", "Caribbean", "North America", 10.6918m, -61.2225m,
                "+1-868", ".tt", "TTD", "Trinidad and Tobago Dollar", "TT$",
                "en", "English", "Port of Spain", "Trinidadian",
                "America/Port_of_Spain", "🇹🇹", 1399491, 5130m),
            CreateCountry("TN", "TUN", "788", "Tunisia", "Tunis", "Republic of Tunisia",
                "Africa", "Northern Africa", "Africa", 33.8869m, 9.5375m,
                "+216", ".tn", "TND", "Tunisian Dinar", "د.ت",
                "ar", "Arabic", "Tunis", "Tunisian",
                "Africa/Tunis", "🇹🇳", 11818618, 163610m),
            CreateCountry("TR", "TUR", "792", "Turkey", "Türkiye", "Republic of Türkiye",
                "Asia", "Western Asia", "Asia", 38.9637m, 35.2433m,
                "+90", ".tr", "TRY", "Turkish Lira", "₺",
                "tr", "Turkish", "Ankara", "Turkish",
                "Europe/Istanbul", "🇹🇷", 84339067, 783562m),
            CreateCountry("TM", "TKM", "795", "Turkmenistan", "Türkmenistan", "Turkmenistan",
                "Asia", "Central Asia", "Asia", 38.9697m, 59.5563m,
                "+993", ".tm", "TMT", "Turkmenistan Manat", "m",
                "tk", "Turkmen", "Ashgabat", "Turkmen",
                "Asia/Ashgabat", "🇹🇲", 6031187, 488100m),
            CreateCountry("TV", "TUV", "798", "Tuvalu", "Tuvalu", "Tuvalu",
                "Oceania", "Polynesia", "Oceania", -7.1095m, 177.6493m,
                "+688", ".tv", "AUD", "Australian Dollar", "$",
                "en", "English,Tuvaluan", "Funafuti", "Tuvaluan",
                "Pacific/Funafuti", "🇹🇻", 11792, 26m),
            CreateCountry("UG", "UGA", "800", "Uganda", "Uganda", "Republic of Uganda",
                "Africa", "Eastern Africa", "Africa", 1.3733m, 32.2903m,
                "+256", ".ug", "UGX", "Ugandan Shilling", "USh",
                "en", "English,Swahili", "Kampala", "Ugandan",
                "Africa/Kampala", "🇺🇬", 45741000, 241038m),
            CreateCountry("UA", "UKR", "804", "Ukraine", "Україна", "Ukraine",
                "Europe", "Eastern Europe", "Europe", 48.3794m, 31.1656m,
                "+380", ".ua", "UAH", "Ukrainian Hryvnia", "₴",
                "uk", "Ukrainian", "Kyiv", "Ukrainian",
                "Europe/Kiev", "🇺🇦", 43733762, 603500m, false),
            CreateCountry("AE", "ARE", "784", "United Arab Emirates", "دولة الإمارات العربية المتحدة",
                "United Arab Emirates",
                "Asia", "Western Asia", "Asia", 23.4241m, 53.8478m,
                "+971", ".ae", "AED", "UAE Dirham", "د.إ",
                "ar", "Arabic", "Abu Dhabi", "Emirati",
                "Asia/Dubai", "🇦🇪", 9890402, 83600m),
            CreateCountry("GB", "GBR", "826", "United Kingdom", "United Kingdom",
                "United Kingdom of Great Britain and Northern Ireland",
                "Europe", "Northern Europe", "Europe", 55.3781m, -3.4360m,
                "+44", ".uk", "GBP", "British Pound", "£",
                "en", "English", "London", "British",
                "Europe/London", "🇬🇧", 67886011, 242900m, false),
            CreateCountry("US", "USA", "840", "United States", "United States", "United States of America",
                "Americas", "Northern America", "North America", 37.0902m, -95.7129m,
                "+1", ".us", "USD", "US Dollar", "$",
                "en", "English", "Washington, D.C.", "American",
                "America/New_York", "🇺🇸", 331002651, 9833517m),
            CreateCountry("UY", "URY", "858", "Uruguay", "Uruguay", "Oriental Republic of Uruguay",
                "Americas", "South America", "South America", -32.5228m, -55.7658m,
                "+598", ".uy", "UYU", "Uruguayan Peso", "$",
                "es", "Spanish", "Montevideo", "Uruguayan",
                "America/Montevideo", "🇺🇾", 3473727, 176215m),
            CreateCountry("UZ", "UZB", "860", "Uzbekistan", "Oʻzbekiston", "Republic of Uzbekistan",
                "Asia", "Central Asia", "Asia", 41.3775m, 64.5853m,
                "+998", ".uz", "UZS", "Uzbekistani Soʻm", "soʻm",
                "uz", "Uzbek", "Tashkent", "Uzbekistani",
                "Asia/Tashkent", "🇺🇿", 33469199, 447400m),
            CreateCountry("VU", "VUT", "548", "Vanuatu", "Vanuatu", "Republic of Vanuatu",
                "Oceania", "Melanesia", "Oceania", -15.3767m, 166.9592m,
                "+678", ".vu", "VUV", "Vatu", "Vt",
                "bi", "Bislama,English,French", "Port Vila", "Ni-Vanuatu",
                "Pacific/Efate", "🇻🇺", 307150, 12189m),
            CreateCountry("VA", "VAT", "336", "Vatican City", "Vaticano", "Vatican City State",
                "Europe", "Southern Europe", "Europe", 41.9029m, 12.4534m,
                "+39", ".va", "EUR", "Euro", "€",
                "it", "Italian,Latin", "Vatican City", "Vatican",
                "Europe/Vatican", "🇻🇦", 825, 0.44m),
            CreateCountry("VE", "VEN", "862", "Venezuela", "Venezuela", "Bolivarian Republic of Venezuela",
                "Americas", "South America", "South America", 6.4238m, -66.5897m,
                "+58", ".ve", "VES", "Bolívar Soberano", "Bs.S.",
                "es", "Spanish", "Caracas", "Venezuelan",
                "America/Caracas", "🇻🇪", 28435943, 916445m),
            CreateCountry("VN", "VNM", "704", "Vietnam", "Việt Nam", "Socialist Republic of Vietnam",
                "Asia", "South-Eastern Asia", "Asia", 14.0583m, 108.2772m,
                "+84", ".vn", "VND", "Vietnamese Dong", "₫",
                "vi", "Vietnamese", "Hanoi", "Vietnamese",
                "Asia/Ho_Chi_Minh", "🇻🇳", 98168833, 331212m),
            CreateCountry("YE", "YEM", "887", "Yemen", "Al-Yaman", "Republic of Yemen",
                "Asia", "Western Asia", "Asia", 15.5527m, 48.5164m,
                "+967", ".ye", "YER", "Yemeni Rial", "﷼",
                "ar", "Arabic", "Sana'a", "Yemeni",
                "Asia/Aden", "🇾🇪", 29825968, 527968m),
            CreateCountry("ZM", "ZMB", "894", "Zambia", "Zambia", "Republic of Zambia",
                "Africa", "Eastern Africa", "Africa", -13.1339m, 27.8493m,
                "+260", ".zm", "ZMW", "Zambian Kwacha", "ZK",
                "en", "English", "Lusaka", "Zambian",
                "Africa/Lusaka", "🇿🇲", 18383956, 752612m),
            CreateCountry("ZW", "ZWE", "716", "Zimbabwe", "Zimbabwe", "Republic of Zimbabwe",
                "Africa", "Southern Africa", "Africa", -19.0154m, 29.1549m,
                "+263", ".zw", "ZWL", "Zimbabwean Dollar", "$",
                "en", "English,Shona,Ndebele", "Harare", "Zimbabwean",
                "Africa/Harare", "🇿🇼", 14862927, 390757m)
        };

        await _dbContext.Countries.AddRangeAsync(countries, cancellationToken);
        await _dbContext.SaveChangesAsync(cancellationToken);

        LogInfo($"Created {countries.Count} countries");
    }

    private static CountryEf CreateCountry(
        string code,
        string alpha3,
        string numeric,
        string name,
        string nativeName,
        string officialName,
        string region,
        string subRegion,
        string continent,
        decimal lat,
        decimal lng,
        string callingCode,
        string tld,
        string currencyCode,
        string currencyName,
        string currencySymbol,
        string primaryLanguage,
        string languages,
        string capital,
        string nationality,
        string timeZones,
        string flag,
        long population,
        decimal area,
        bool isEuMember = false,
        bool isUnMember = true,
        bool isIndependent = true)
    {
        return new CountryEf
        {
            Code = code,
            Alpha3Code = alpha3,
            NumericCode = numeric,
            Name = name,
            NativeName = nativeName,
            OfficialName = officialName,
            Region = region,
            SubRegion = subRegion,
            Continent = continent,
            Latitude = lat,
            Longitude = lng,
            CallingCode = callingCode,
            TopLevelDomain = tld,
            CurrencyCode = currencyCode,
            CurrencyName = currencyName,
            CurrencySymbol = currencySymbol,
            PrimaryLanguage = primaryLanguage,
            Languages = languages,
            Capital = capital,
            Nationality = nationality,
            TimeZones = timeZones,
            Flag = flag,
            Population = population,
            Area = area,
            IsActive = true,
            IsEUMember = isEuMember,
            IsUNMember = isUnMember,
            IsIndependent = isIndependent
        };
    }
}
